---
title: "Cyber Insurance Modelthon Workbook"
output: html_notebook
---

```{r eval=FALSE, include=FALSE}
###Run this chunk once manually in the beginnig to install the necessary packages

require("data.table")
require("tidyverse")
require("formattable")
require("actuar")
```

```{r}
#Libraries
library(data.table)
library(tidyverse)
library(formattable)
library(actuar)
library(forcats)

wd = getwd()


#Loading DAmage, Premium and Expense Ratio Data
load(paste0(wd,"/data/Input_Data_Modelthon.RData"))

#Loading Solutions First Optimizaton
load(paste0(wd,"/data/solution_model_1.RData"))

#Loading Data for Second Optimization
load(paste0(wd,"/data/solution_model_2.RData"))

#Loading Data for premium
load(paste0(wd,"/data/premiumarray.RData"))

load(paste0(wd,"/data/71-buckets.RData"))
#Load Data constrained Optimization
load(paste0(wd,"/data/constrained.RData"))

#load ILS Scenario Data
load(paste0(wd,"/data/ils_scenario_data.RData"))

#load ILS Scenario Primary Insurer "Beazley"


#Hardcoded IW-Arrays
scenario_1_IW = c(5e3,2.5e3,1.5e3,1.25e3,0.7e3) 
scenario_2_IW = c(6:15*1e3)
scenario_3_IW = c(5e3,2.5e3,1.5e3,1.25e3,0.7e3) 
scenario_4_IW = c(3e4)
scenario_4_CC_IW = c(3e4,3.5e4,4e4,4.5e4,5e4 )

#More Information:
#Scenario 1: Standard Optimization, No Constraints
#Scenario 2: One Insurer per 
#Scenario 3: 5 Insurance Companies, First and Second constrained to Large, Third to Med, Fourth and Fifth Small & Med
#Scenario 4: Cyber ILS Bond of big Primary Insurer with ~1.2B GWP
```

```{r}
#Function to query coalition data 
library(googlesheets4)
load_coalition_data <- function() {
  
  gs4_deauth()
  data <- read_sheet("https://docs.google.com/spreadsheets/d/18XwUZXET9ZsEyYHevRwxreuFejoAlFxBSEf9r3mkwR8/edit?usp=drive_web&ouid=113610088129293170193")
  return(data)
}
```

```{r}
#' Calculate the outcomes from the best weights of the optimization and the respective weights of insurance companies 
#'
#' @author Daniel Kasper <daniel.kasper@@cyber-economics.com>
#'
#' @param weights 2-Dimensional Array with the outcomes of main simulation or manually set weights. Needs to be fed all Insurance Companies for a given model.
#' @param verification_Set Verification set with "fresh" data to verifiy to main optimization results on.Number of Rows equal to number of Columns of optimal weights for Matrix Multiplication.
#' @output Returns a list with the VaR, average return, many more summary statistics and a data.frame with the outcomes in the long (=dplyr & ggplot2 friendly) format.
#' @param mode Integer where 1 returns additional values used by higher order functions and 0 returns just the result

calculate_insurance_outcomes <- function(weights,verification_set,initial_wealth_array, mode){
  #Get Result Dimensions from the dimension of the weight
  num_IC =  dim(weights)[3]
  num_sim_runs =  dim(weights)[1]
  result_matrix <- data.frame(matrix(ncol = num_IC, nrow = 7))
  #Write Initial Capital 
  result_matrix[1,] = initial_wealth_array
  rownames(result_matrix) <- c("Initial Wealth (IW)", "Avg. VaR 99.5% (RP200)", "Sum of VaR-Violations", "Avg. Profit", "Model Premium", "Implied Expense Ratio", "Avg. Probability of Loss" )
  n_runs =  ncol(verification_set)
  for (i in 1:num_IC){
    
    VaR = 0 
    realized_result = 0
    model_premium_without_expense_ratio = 0 
    implied_premiums_with_expense_ratio = 0
    VaR_Penalty_Sum = 0
    probability_of_loss = 0
    
        for (k in 1:num_sim_runs){
   #Get Active weights.
           active_weight = weights[k,,i]
  
            'Calculate Return'
  returnvector <- colSums(active_weight %*% verification_set)
    
    #First Append Data, so it can be used for the reinsurance case later as well with     # a static id to map correlation.
    
        if(i*k == 1){ 
       statistical_distributions =    as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs)))
         colnames(statistical_distributions) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch") 
    } else {
      new_rows = as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs)))
      colnames(new_rows) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch") 
      statistical_distributions = rbind(statistical_distributions, new_rows)
      
        
      }
    

  returnvector = sort(returnvector, decreasing = T)
  #Get Number of runs to calculate Var 99.5. Algorithm: Divide n_runs by 200 and multiply this number by 199 (position of VAR) rounded up
  n_runs =  ncol(verification_set)
  VAR_position = ceiling((n_runs / 200)* 199)
  VaR <- returnvector[VAR_position] + VaR
  realized_result <- mean(returnvector)
  #Premiums need to be scaled down by 1000. The model premium is calculated by 
  model_premium_without_expense_ratio = (colSums(active_weight %*% (premium_array))) + model_premium_without_expense_ratio
 
  #With the expenseratio added
  implied_premiums_with_expense_ratio = (colSums(active_weight %*% (premium_array))) /0.7 + implied_premiums_with_expense_ratio
probability_of_loss = (length(returnvector[returnvector < 0]) / n_runs) + probability_of_loss

    VaR_Penalty_Sum = ifelse(initial_wealth_array[i] < -returnvector[VAR_position],1,0) + VaR_Penalty_Sum
    #Create Dataframe with data in long format. if i*k=1 (first loop) create new df, else append to existing.

    
    #End Inner Loop
        }
    
    result_matrix[2,i] = VaR / num_sim_runs
    result_matrix[3,i] = VaR_Penalty_Sum / num_sim_runs
    result_matrix[4,i] = realized_result / num_sim_runs
    result_matrix[5,i] = model_premium_without_expense_ratio / num_sim_runs
    result_matrix[6,i] = implied_premiums_with_expense_ratio / num_sim_runs
    result_matrix[7,i] = probability_of_loss / num_sim_runs
     
    
  }
  if (mode == 0) { 
    output = list(result_matrix,statistical_distributions)
    names(output) = c("Summary_Statistics", "Outcomes_Long_Format")
    }
  else{
    output = list(result_matrix,statistical_distributions, returnvector)
    names(output) = c("Summary_Statistics", "Outcomes_Long_Format", "Return Vector")
  }
  return(output)
}
```

```{r}
#' Calculate the outcomes from the best weights of the optimization and the respective weights of insurance companies 
#'
#' @author Daniel Kasper <daniel.kasper@@cyber-economics.com>
#'
#' @param weights 2-Dimensional Array with the outcomes of main simulation or manually set weights. Needs to be fed all Insurance Companies for a given model. But instead of a single weight, all relevant insurance companies in a given model scenario need to be supplied, otherwise, reinsurance wouldn't make sense.
#' @param verification_Set Verification set with "fresh" data to verify to main optimization results on.Number of Rows equal to number of Columns of optimal weights for Matrix Multiplication.
#' @param reinsurance_matrix A Reinsurance matrix with number of insurance companies equal to the columns 
#' @output Returns a list with tons of good stuff!
#'
calculate_reinsurance_outcomes <- function(weights, verification_set, initial_wealth_array, reinsurance_matrix, mode){

 num_IC =  dim(weights)[3]
 num_sim_runs =  dim(weights)[1]
 insurance_outcome = calculate_insurance_outcomes(weights, verification_set, initial_wealth_array, 1)
 statistical_distributions = insurance_outcome[[2]]
 returnvector = insurance_outcome[[3]]
    #Code Equal to insurance_outcomes function at the end.
#   num_IC =  dim(weights)[3]
#   num_sim_runs =  dim(weights)[1]
#   result_matrix <- data.frame(matrix(ncol = num_IC, nrow = 7))
#   #Write Initial Capital 
#   result_matrix[1,] = initial_wealth_array
#   rownames(result_matrix) <- c("Initial Wealth (IW)", "Avg. VaR 99.5% (RP200)", "Sum of VaR-Violations", "Avg. Profit", "Model Premium", "Premium with Expense Ratio", "Avg. Probability of Loss" )
#   n_runs =  ncol(verification_set)
#   for (i in 1:num_IC){
#     
#     VaR = 0 
#     realized_result = 0
#     model_premium_without_expense_ratio = 0 
#     implied_premiums_with_expense_ratio = 0
#     VaR_Penalty_Sum = 0
#     probability_of_loss = 0
#     
#         for (k in 1:num_sim_runs){
#    #Get Active weights.
#            active_weight = weights[k,,i]
#   
#             'Calculate Return'
#   returnvector <- colSums(active_weight %*% verification_set)
#     
#     #First Append Data, so it can be used for the reinsurance case later as well with     # a static id to map correlation.
#     
#         if(i*k == 1){ 
#        statistical_distributions =    as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
#          colnames(statistical_distributions) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch", "Number_IC")   
#     } else {
#       new_rows = as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
#       colnames(new_rows) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch", "Number_IC") 
#       statistical_distributions = rbind(statistical_distributions, new_rows)
#       
#         
#       }
#     
# 
#   returnvector = sort(returnvector, decreasing = T)
#   #Get Number of runs to calculate Var 99.5. Algorithm: Divide n_runs by 200 and multiply this number by 199 (position of VAR) rounded up
#   n_runs =  ncol(verification_set)
#   VAR_position = ceiling((n_runs / 200)* 199)
#   VaR <- returnvector[VAR_position] + VaR
#   realized_result <- mean(returnvector)
#   #Premiums need to be scaled down by 1000. The model premium is calculated by 
#   model_premium_without_expense_ratio = (colSums(active_weight %*% (premium_array))) + model_premium_without_expense_ratio
#   #With the expenseratio added
#   implied_premiums_with_expense_ratio = (colSums(active_weight %*% (premium_array))) /0.7 + implied_premiums_with_expense_ratio
# probability_of_loss = (length(returnvector[returnvector < 0]) / n_runs) + probability_of_loss
# 
#     VaR_Penalty_Sum = ifelse(initial_wealth_array[i] < -returnvector[VAR_position],1,0) + VaR_Penalty_Sum
#     #Create Dataframe with data in long format. if i*k=1 (first loop) create new df, else append to existing.
# 
#     
#     #End Inner Loop
#         }
#     
#     result_matrix[2,i] = VaR / num_sim_runs
#     result_matrix[3,i] = VaR_Penalty_Sum 
#     result_matrix[4,i] = realized_result / num_sim_runs
#     result_matrix[5,i] = model_premium_without_expense_ratio / num_sim_runs
#     result_matrix[6,i] = implied_premiums_with_expense_ratio / num_sim_runs
#     result_matrix[7,i] = probability_of_loss / num_sim_runs
#     
#    
#     
#     
#   }
#   
# output_insurance = list(result_matrix,statistical_distributions)
# names(output_insurance) = c("Summary_Statistics", "Outcomes_Long_Format")


#Start the Reinsurance specific Analysis here
#Number of reinsurance Companies
num_rc = nrow(reinsurance_matrix)

#Declare Reinsurance Matrix Summary 

  reinsurance_result_matrix <- data.frame(matrix(ncol = num_rc, nrow = 5))
  #Write Initial Capital 
  rownames(reinsurance_result_matrix) <- c("Avg. VaR 99.5% (RP200)","Avg. Profit", "Primary Model Premium Share", "Premium with Expense Ratio", "Avg. Probability of Loss" )

for (i in 1:num_rc){

#Get Correct reinsurance weight for each company.
reinsurance_weights = cbind(c(1:num_IC),reinsurance_matrix[i,])
colnames(reinsurance_weights) = c("Number_IC", "Quota_Share")

#Get the Reinsurance Losses by looking up the Quota_Shares from the reinsurer
reinsurance_outcomes = statistical_distributions %>%  ungroup() %>% left_join(reinsurance_weights, copy = T,by = c("Simulation_Number" = "Number_IC")) %>% mutate(Reinsurance_profit = Quota_Share * Profit) %>% group_by(Simulation_Number,Damage_Year_Epoch) %>% summarize(reinsurance_epoch_loss = sum(Reinsurance_profit)) %>% group_by(Simulation_Number) %>% group_split

#Iterate through the simulation runs to calculate reinsurance outcomes
    VaR = 0 
    realized_result = 0
    Primary_Premium_Share =  0 
    probability_of_loss = 0
 
for(k in 1:num_sim_runs){
reinsurance_return_vector = sort(reinsurance_outcomes[[k]][["reinsurance_epoch_loss"]])

#Write Reinsurance Outcomes to Data, fit to reinsurance

        if(i*k == 1){ 
       statistical_distributions_reinsurance =    as.data.frame(cbind(returnvector, rep(paste0((reinsurance_matrix[i,])), n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(statistical_distributions_reinsurance) <- c("Profit", "List_of_Weights", "Simulation_Number", "Damage_Year/Epoch", "Number_RC")   
    } else {
      new_rows = as.data.frame(cbind(returnvector, rep(paste0((reinsurance_matrix[i,])), n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(new_rows) <- c("Profit", "List_of_Weights", "Simulation_Number", "Damage_Year/Epoch", "Number_RC") 
      statistical_distributions_reinsurance = rbind(statistical_distributions_reinsurance, new_rows)
      
        
      }
#Array is flipped_so need 
n_runs =  length(reinsurance_return_vector)
VAR_position = n_runs - ceiling((n_runs / 200)* 199)
VaR <- reinsurance_return_vector[VAR_position] + VaR
realized_result <- mean(reinsurance_return_vector)  
probability_of_loss = (length(returnvector[reinsurance_return_vector < 0]) / n_runs) + probability_of_loss
 
}
    #lazy loop
     reinsurance_premium_share  = 0
    for (j in 1:num_IC){
    reinsurance_premium_share = reinsurance_matrix[i,j] * output_insurance[[1]][5,j] + reinsurance_premium_share
    }
    reinsurance_result_matrix[1,i] = VaR / num_sim_runs
    reinsurance_result_matrix[2,i] = realized_result / num_sim_runs
    reinsurance_result_matrix[3,i] = reinsurance_premium_share
    reinsurance_result_matrix[4,i] = reinsurance_premium_share / 0.7
    reinsurance_result_matrix[5,i] = probability_of_loss / num_sim_runs


}

 output_reinsurance = list(reinsurance_result_matrix, statistical_distributions_reinsurance)

 final_output = list(output_insurance,output_reinsurance)
 names(final_output) = list("Insurance Outcomes", "Reinsurance Outcomes")



return(final_output)
}
```

```{r}
#' Calculate the outcomes from the best weights of the optimization and the respective weights of insurance companies 
#'
#' @author Daniel Kasper <daniel.kasper@@cyber-economics.com>
#'
#' @param weights 2-Dimensional Array with the outcomes of main simulation or manually set weights. Needs to be fed all Insurance Companies for a given model. But instead of a single weight, all relevant insurance companies in a given model scenario need to be supplied, otherwise, reinsurance wouldn't make sense.
#' @param verification_Set Verification set with "fresh" data to verify to main optimization results on.Number of Rows equal to number of Columns of optimal weights for Matrix Multiplication.
#' @param reinsurance_matrix A Reinsurance matrix with number of insurance companies equal to the columns 
#' @output Returns a list with tons of good stuff!
#'
calculate_reinsurance_ils_outcomes <- function(weights, verification_set, initial_wealth_array, reinsurance_matrix,bond_value,target_sharpe_ratio, risk_free_rate){
   #Code Equal to insurance_outcomes function at the end.
  num_IC =  dim(weights)[3]
  num_sim_runs =  dim(weights)[1]
  result_matrix <- data.frame(matrix(ncol = num_IC, nrow = 7))
  #Write Initial Capital 
  result_matrix[1,] = initial_wealth_array
  rownames(result_matrix) <- c("Initial Wealth (IW)", "Avg. VaR 99.5% (RP200)", "Sum of VaR-Violations", "Avg. Profit", "Model Premium", "Premium with Expense Ratio", "Avg. Probability of Loss" )
  n_runs =  ncol(verification_set)
  for (i in 1:num_IC){
    
    VaR = 0 
    realized_result = 0
    model_premium_without_expense_ratio = 0 
    implied_premiums_with_expense_ratio = 0
    VaR_Penalty_Sum = 0
    probability_of_loss = 0
    
        for (k in 1:num_sim_runs){
   #Get Active weights.
           active_weight = weights[k,,i]
  
            'Calculate Return'
  returnvector <- colSums(active_weight %*% verification_set)
    
    #First Append Data, so it can be used for the reinsurance case later as well with     # a static id to map correlation.
    
        if(i*k == 1){ 
       statistical_distributions =    as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(statistical_distributions) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch", "Number_IC")   
    } else {
      new_rows = as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
      colnames(new_rows) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch", "Number_IC") 
      statistical_distributions = rbind(statistical_distributions, new_rows)
      
        
      }
    

  returnvector = sort(returnvector, decreasing = T)
  #Get Number of runs to calculate Var 99.5. Algorithm: Divide n_runs by 200 and multiply this number by 199 (position of VAR) rounded up
  n_runs =  ncol(verification_set)
  VAR_position = ceiling((n_runs / 200)* 199)
  VaR <- returnvector[VAR_position] + VaR
  realized_result <- mean(returnvector)
  #Premiums need to be scaled down by 1000. The model premium is calculated by 
  model_premium_without_expense_ratio = (colSums(active_weight %*% (premium_array))) + model_premium_without_expense_ratio
  #With the expenseratio added
  implied_premiums_with_expense_ratio = (colSums(active_weight %*% (premium_array))) /0.7 + implied_premiums_with_expense_ratio
probability_of_loss = (length(returnvector[returnvector < 0]) / n_runs) + probability_of_loss

    VaR_Penalty_Sum = ifelse(initial_wealth_array[i] < -returnvector[VAR_position],1,0) + VaR_Penalty_Sum
    #Create Dataframe with data in long format. if i*k=1 (first loop) create new df, else append to existing.

    
    #End Inner Loop
        }
    
    result_matrix[2,i] = VaR / num_sim_runs
    result_matrix[3,i] = VaR_Penalty_Sum 
    result_matrix[4,i] = realized_result / num_sim_runs
    result_matrix[5,i] = model_premium_without_expense_ratio / num_sim_runs
    result_matrix[6,i] = implied_premiums_with_expense_ratio / num_sim_runs
    result_matrix[7,i] = probability_of_loss / num_sim_runs
    
   
    
    
  }
  
output_insurance = list(result_matrix,statistical_distributions)
names(output_insurance) = c("Summary_Statistics", "Outcomes_Long_Format")

#Start the Reinsurance specific Analysis here
#Number of reinsurance Companies
num_rc = nrow(reinsurance_matrix)

#Declare Reinsurance Matrix Summary 

  reinsurance_result_matrix <- data.frame(matrix(ncol = num_rc, nrow = 5))
  #Write Initial Capital 
  rownames(reinsurance_result_matrix) <- c("Avg. VaR 99.5% (RP200)","Avg. Profit", "Primary Model Premium Share", "Premium with Expense Ratio", "Avg. Probability of Loss" )

for (i in 1:num_rc){

#Get Correct reinsurance weight for each company.
reinsurance_weights = cbind(c(1:num_IC),reinsurance_matrix[i,])
colnames(reinsurance_weights) = c("Number_IC", "Quota_Share")

#Get the Reinsurance Losses by looking up the Quota_Shares from the reinsurer
reinsurance_outcomes = statistical_distributions %>%  ungroup() %>% left_join(reinsurance_weights, copy = T) %>% mutate(Reinsurance_profit = Quota_Share * Profit) %>% group_by(Simulation_Number,Damage_Year_Epoch) %>% summarize(reinsurance_epoch_loss = sum(Reinsurance_profit)) %>% group_by(Simulation_Number) %>% group_split

#Iterate through the simulation runs to calculate reinsurance outcomes
    VaR = 0 
    realized_result = 0
    Primary_Premium_Share =  0 
    probability_of_loss = 0
 
for(k in 1:num_sim_runs){
reinsurance_return_vector = sort(reinsurance_outcomes[[k]][["reinsurance_epoch_loss"]])

#Write Reinsurance Outcomes to Data, fit to reinsurance

        if(i*k == 1){ 
       statistical_distributions_reinsurance =    as.data.frame(cbind(reinsurance_return_vector, rep(paste0((reinsurance_matrix[i,])), n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(statistical_distributions_reinsurance) <- c("Profit", "List_of_Weights", "Simulation_Number", "Damage_Year/Epoch", "Number_RC")   
    } else {
      new_rows = as.data.frame(cbind(reinsurance_return_vector, rep(paste0((reinsurance_matrix[i,])), n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(new_rows) <- c("Profit", "List_of_Weights", "Simulation_Number", "Damage_Year/Epoch", "Number_RC") 
      statistical_distributions_reinsurance = rbind(statistical_distributions_reinsurance, new_rows)
      
        
      }
#Array is flipped so need to reflip 
n_runs =  length(reinsurance_return_vector)
VAR_position = n_runs - ceiling((n_runs / 200)* 199)
VaR <- reinsurance_return_vector[VAR_position] + VaR
realized_result <- mean(reinsurance_return_vector)  
probability_of_loss = (length(returnvector[reinsurance_return_vector < 0]) / n_runs) + probability_of_loss
 
}
    #lazy loop
     reinsurance_premium_share  = 0
    for (j in 1:num_IC){
    reinsurance_premium_share = reinsurance_matrix[i,j] * output_insurance[[1]][5,j] + reinsurance_premium_share
    }
    reinsurance_result_matrix[1,i] = VaR / num_sim_runs
    reinsurance_result_matrix[2,i] = realized_result / num_sim_runs
    reinsurance_result_matrix[3,i] = reinsurance_premium_share
    reinsurance_result_matrix[4,i] = reinsurance_premium_share / 0.7
    reinsurance_result_matrix[5,i] = probability_of_loss / num_sim_runs


}

 output_reinsurance = list(reinsurance_result_matrix, statistical_distributions_reinsurance)

 ### ILS Loop. Calculate the Ex-post expected value and variance, then calculate bond coupon payments.
 ### Logic: filter down all outcomes below the VaR, then build expected bond payouts to get fair 
 ### fair price. To do that, add the respective VaR to the reinsurance matrix. First build an array
 ### Consisting of the RC number and VaR to map, then filter and map.

 reinsurance_var_array = data.frame(matrix(1:(2*num_rc), ncol = 2, nrow = num_rc))
 colnames(reinsurance_var_array) <- c("Number_RC", "VAR99.5")
 for (i in 1:num_rc){
   reinsurance_var_array[i,1] = i
   reinsurance_var_array[i,2] = reinsurance_result_matrix[1,i]
 }
 
 reinsurance_var_array[,1] = sapply(reinsurance_var_array[,1], as.factor)

 #Create Lookup Bond Array
 
 bond_value = data.frame(cbind(1:length(bond_value),bond_value))
 colnames(bond_value) <- c("Number_RC", "Cyber_Bond_Value")
  bond_value[,1] = sapply(bond_value[,1], as.factor)
 
#Lookup VaR and Bond Value
 bond_outcomes =  statistical_distributions_reinsurance %>% left_join(reinsurance_var_array, by = c("Number_RC" = "Number_RC"), copy = T) %>% left_join(bond_value, by = c("Number_RC" = "Number_RC"), copy = T)


 #Calculate excess loss payout & residual (=PPP Scheme)
 bond_outcomes = bond_outcomes %>% group_by() %>% mutate(
   excess_var_loss = ifelse(VAR99.5 - as.numeric(Profit) > 0,VAR99.5 - as.numeric(Profit),0),
   bond_loss = ifelse(excess_var_loss > Cyber_Bond_Value, Cyber_Bond_Value,excess_var_loss),
   excess_uninsured_loss = excess_var_loss - bond_loss,
  
   
 )
#Calculate Bond Expected Losses. To get the EVs, group by the respectice Reinsurer (1 bond for 1 #reinsurer) and divide the sum of bond_losses by the number of simulation runs times the sample size
# of the verification set (32k).

 
 bond_statistics = bond_outcomes %>% group_by(Number_RC) %>% summarize(
 absolute_expected_loss_bonds = sum(bond_loss)/(num_sim_runs*n_runs),
 relative_expected_loss = absolute_expected_loss_bonds/mean(Cyber_Bond_Value),
 sd_loss_bonds = sd(bond_loss),
 #Target Sharpe Ratio solved for coupon payments = TRSR * VAR + EV(Return) + Risk Free Rate
 coupon_payment = target_sharpe_ratio * sd_loss_bonds + absolute_expected_loss_bonds + risk_free_rate,
 Return_On_Equity_Investors = coupon_payment/mean(Cyber_Bond_Value),
 sum_uninsured_losses =  sum(excess_uninsured_loss)/(num_sim_runs*n_runs),
 Probability_of_bond_payout = ifelse(bond_loss > 0,1,0)/(num_sim_runs*n_runs),
 Probability_of_excess_loss = ifelse(excess_uninsured_loss > 0,1,0)/(num_sim_runs*n_runs)
 )



ILS_output = list(bond_statistics,bond_outcomes)
 
 
 
 final_output = list(output_insurance,output_reinsurance,bond_outcomes,ILS_output)
 names(final_output) = list("Insurance Outcomes", "Reinsurance Outcomes", "ILS Outcomes")



return(final_output)
}
```

```{r}
#' Calculate the outcomes from the best weights of the optimization and the respective weights of insurance companies 
#'
#' @author Daniel Kasper <daniel.kasper@@cyber-economics.com>
#'
#' @param weights 2-Dimensional Array with the outcomes of main simulation or manually set weights. Needs to be fed all Insurance Companies for a given model. But instead of a single weight, all relevant insurance companies in a given model scenario need to be supplied, otherwise, reinsurance wouldn't make sense.
#' @param verification_Set Verification set with "fresh" data to verify to main optimization results on.Number of Rows equal to number of Columns of optimal weights for Matrix Multiplication.
#' @param reinsurance_matrix A Reinsurance matrix with number of insurance companies equal to the columns 
#' @output Returns a list with tons of good stuff!
#'
calculate_reinsurance_ils_hypothetical_bond_outcome <- function(weights, verification_set, initial_wealth_array, reinsurance_matrix,bond_value,target_sharpe_ratio, risk_free_rate, VaR_Position_ILS){
   #Code Equal to insurance_outcomes function at the end.
  num_IC =  dim(weights)[3]
  num_sim_runs =  dim(weights)[1]
  result_matrix <- data.frame(matrix(ncol = num_IC, nrow = 7))
  #Write Initial Capital 
  result_matrix[1,] = initial_wealth_array
  rownames(result_matrix) <- c("Initial Wealth (IW)", "Avg. VaR 99.5% (RP200)", "Sum of VaR-Violations", "Avg. Profit", "Model Premium", "Premium with Expense Ratio", "Avg. Probability of Loss" )
  print(1)
  n_runs =  ncol(verification_set)
  for (i in 1:num_IC){
    
    VaR = 0 
    realized_result = 0
    model_premium_without_expense_ratio = 0 
    implied_premiums_with_expense_ratio = 0
    VaR_Penalty_Sum = 0
    probability_of_loss = 0
    
        for (k in 1:num_sim_runs){
   #Get Active weights.
           active_weight = weights[k,,i]
  
            'Calculate Return'
  returnvector <- colSums(active_weight %*% verification_set)
    
    #First Append Data, so it can be used for the reinsurance case later as well with     # a static id to map correlation.
    
        if(i*k == 1){ 
       statistical_distributions =    as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(statistical_distributions) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch", "Number_IC")   
    } else {
      new_rows = as.data.frame(cbind(returnvector, rep(initial_wealth_array[i], n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
      colnames(new_rows) <- c("Profit", "Initial_Wealth", "Simulation_Number", "Damage_Year_Epoch", "Number_IC") 
      statistical_distributions = rbind(statistical_distributions, new_rows)
      
        
      }
    

  returnvector = sort(returnvector, decreasing = T)
  #Get Number of runs to calculate Var 99.5. Algorithm: Divide n_runs by 200 and multiply this number by 199 (position of VAR) rounded up
  n_runs =  ncol(verification_set)
  VAR_position = ceiling((n_runs / 200)* 199)
  VaR <- returnvector[VAR_position] + VaR
  realized_result <- mean(returnvector)
  #Premiums need to be scaled down by 1000. The model premium is calculated by 
  model_premium_without_expense_ratio = (colSums(active_weight %*% (premium_array))) + model_premium_without_expense_ratio
  #With the expenseratio added
  implied_premiums_with_expense_ratio = (colSums(active_weight %*% (premium_array))) /0.7 + implied_premiums_with_expense_ratio
probability_of_loss = (length(returnvector[returnvector < 0]) / n_runs) + probability_of_loss

    VaR_Penalty_Sum = ifelse(initial_wealth_array[i] < -returnvector[VAR_position],1,0) + VaR_Penalty_Sum
    #Create Dataframe with data in long format. if i*k=1 (first loop) create new df, else append to existing.

    
    #End Inner Loop
        }
    
    result_matrix[2,i] = VaR / num_sim_runs
    result_matrix[3,i] = VaR_Penalty_Sum 
    result_matrix[4,i] = realized_result / num_sim_runs
    result_matrix[5,i] = model_premium_without_expense_ratio / num_sim_runs
    result_matrix[6,i] = implied_premiums_with_expense_ratio / num_sim_runs
    result_matrix[7,i] = probability_of_loss / num_sim_runs
    
   
    
    
  }
  
output_insurance = list(result_matrix,statistical_distributions)
names(output_insurance) = c("Summary_Statistics", "Outcomes_Long_Format")

#Start the Reinsurance specific Analysis here
#Number of reinsurance Companies
num_rc = nrow(reinsurance_matrix)

#Declare Reinsurance Matrix Summary 

  reinsurance_result_matrix <- data.frame(matrix(ncol = num_rc, nrow = 5))
  #Write Initial Capital 

  rownames(reinsurance_result_matrix) <- c("Avg. VaR 99.5% (RP200)","Avg. Profit", "Primary Model Premium Share", "Premium with Expense Ratio", "Avg. Probability of Loss" )
 

for (i in 1:num_rc){

#Get Correct reinsurance weight for each company.
reinsurance_weights = cbind(c(1:num_IC),reinsurance_matrix[i,])
colnames(reinsurance_weights) = c("Number_IC", "Quota_Share")

#Get the Reinsurance Losses by looking up the Quota_Shares from the reinsurer
reinsurance_outcomes = statistical_distributions %>%  ungroup() %>% left_join(reinsurance_weights, copy = T) %>% mutate(Reinsurance_profit = Quota_Share * Profit) %>% group_by(Simulation_Number,Damage_Year_Epoch) %>% summarize(reinsurance_epoch_loss = sum(Reinsurance_profit)) %>% group_by(Simulation_Number) %>% group_split

#Iterate through the simulation runs to calculate reinsurance outcomes
    VaR = 0 
    realized_result = 0
    Primary_Premium_Share =  0 
    probability_of_loss = 0
 
for(k in 1:num_sim_runs){
reinsurance_return_vector = sort(reinsurance_outcomes[[k]][["reinsurance_epoch_loss"]])

#Write Reinsurance Outcomes to Data, fit to reinsurance

        if(i*k == 1){ 
       statistical_distributions_reinsurance =    as.data.frame(cbind(reinsurance_return_vector, rep(paste0((reinsurance_matrix[i,])), n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(statistical_distributions_reinsurance) <- c("Profit", "List_of_Weights", "Simulation_Number", "Damage_Year/Epoch", "Number_RC")   
    } else {
      new_rows = as.data.frame(cbind(reinsurance_return_vector, rep(paste0((reinsurance_matrix[i,])), n_runs), rep(k, n_runs), c(1:n_runs), rep(i,n_runs)))
         colnames(new_rows) <- c("Profit", "List_of_Weights", "Simulation_Number", "Damage_Year/Epoch", "Number_RC") 
      statistical_distributions_reinsurance = rbind(statistical_distributions_reinsurance, new_rows)
      
        
      }
#Array is flipped so need to reflip 
n_runs =  length(reinsurance_return_vector)
adjusted_position = VaR_Position_ILS * 200
VAR_position = n_runs - ceiling((n_runs / 200)* adjusted_position)
VaR <- reinsurance_return_vector[VAR_position] + VaR
realized_result <- mean(reinsurance_return_vector)  
probability_of_loss = (length(returnvector[reinsurance_return_vector < 0]) / n_runs) + probability_of_loss
 
}
    #lazy loop
     reinsurance_premium_share  = 0
    for (j in 1:num_IC){
    reinsurance_premium_share = reinsurance_matrix[i,j] * output_insurance[[1]][5,j] + reinsurance_premium_share
    }
    reinsurance_result_matrix[1,i] = VaR / num_sim_runs
    reinsurance_result_matrix[2,i] = realized_result / num_sim_runs
    reinsurance_result_matrix[3,i] = reinsurance_premium_share
    reinsurance_result_matrix[4,i] = reinsurance_premium_share / 0.7
    reinsurance_result_matrix[5,i] = probability_of_loss / num_sim_runs


}

 output_reinsurance = list(reinsurance_result_matrix, statistical_distributions_reinsurance)

 ### ILS Loop. Calculate the Ex-post expected value and variance, then calculate bond coupon payments.
 ### Logic: filter down all outcomes below the VaR, then build expected bond payouts to get fair 
 ### fair price. To do that, add the respective VaR to the reinsurance matrix. First build an array
 ### Consisting of the RC number and VaR to map, then filter and map.

 reinsurance_var_array = data.frame(matrix(1:(2*num_rc), ncol = 2, nrow = num_rc))
 colnames(reinsurance_var_array) <- c("Number_RC", "VAR99.5")
 for (i in 1:num_rc){
   reinsurance_var_array[i,1] = i
   reinsurance_var_array[i,2] = reinsurance_result_matrix[1,i]
 }
 
 reinsurance_var_array[,1] = sapply(reinsurance_var_array[,1], as.factor)

 #Create Lookup Bond Array
 
 bond_value = data.frame(cbind(1:length(bond_value),bond_value))
 colnames(bond_value) <- c("Number_RC", "Cyber_Bond_Value")
  bond_value[,1] = sapply(bond_value[,1], as.factor)
 
#Lookup VaR and Bond Value
 bond_outcomes =  statistical_distributions_reinsurance %>% left_join(reinsurance_var_array, by = c("Number_RC" = "Number_RC"), copy = T) %>% left_join(bond_value, by = c("Number_RC" = "Number_RC"), copy = T)


 #Calculate excess loss payout & residual (=PPP Scheme)
 bond_outcomes = bond_outcomes %>% group_by() %>% mutate(
   excess_var_loss = ifelse(VAR99.5 - as.numeric(Profit) > 0,VAR99.5 - as.numeric(Profit),0),
   bond_loss = ifelse(excess_var_loss > Cyber_Bond_Value, Cyber_Bond_Value,excess_var_loss),
   excess_uninsured_loss = excess_var_loss - bond_loss,
  
   
 )
#Rename VAR with the Correct VaR that is used.
 
adjusted_Var_name = paste0("VAR",VaR_Position_ILS*100)
names(bond_outcomes)[names(bond_outcomes) == 'VAR99.5'] <- "adjusted_Var_name" 

#Calculate Bond Expected Losses. To get the EVs, group by the respectice Reinsurer (1 bond for 1 #reinsurer) and divide the sum of bond_losses by the number of simulation runs times the sample size
# of the verification set (32k).

 
 bond_statistics = bond_outcomes %>% ungroup() %>% group_by(Number_RC) %>% summarize(
   Cyber_Bond_Value = mean(Cyber_Bond_Value),
 absolute_expected_loss_bonds = mean(bond_loss),
 relative_expected_loss = mean(absolute_expected_loss_bonds/Cyber_Bond_Value),
 sd_loss_bonds = sd(bond_loss),
 #Target Sharpe Ratio solved for coupon payments = TRSR * VAR + EV(Return) + Risk Free Rate
coupon_payment = target_sharpe_ratio * sd_loss_bonds + absolute_expected_loss_bonds + risk_free_rate,
Return_On_Equity_Investors = coupon_payment/Cyber_Bond_Value,
sum_uninsured_losses =  mean(excess_uninsured_loss),
Attatchment_Probability_Bond = mean(ifelse(bond_loss > 0,1,0)),
Probability_of_excess_loss = mean(ifelse(excess_uninsured_loss > 0,1,0))
 )







ILS_output = list(bond_statistics,bond_outcomes)
 
 
 
 final_output = list(output_insurance,output_reinsurance,ILS_output)
 names(final_output) = list("Insurance Outcomes", "Reinsurance Outcomes", "ILS Outcomes")



return(final_output)
}
```

```{r}
#Graphic Functions
plot_insurance_distributions <- function(insurance_object){
df_to_plot = insurance_object[[1]][[2]]
for(IW in unique(df_to_plot$Initial_Wealth)){
p = ggplot()
colors = c("red","blue","green","yellow","black")
for(simu_nb in seq(1,5)){
  df_to_plot_simu_1= df_to_plot[df_to_plot$Simulation_Number== simu_nb,]%>% filter(Initial_Wealth == IW) %>% arrange(Profit)
p = p + theme_bw() + geom_line(data = df_to_plot_simu_1,aes(y=Profit,x=seq(1,length(Profit))),color = colors[simu_nb], label = paste0("simulation_nb",str(simu_nb)))+ggtitle(paste0("Profits by simulations for initial wealth = ",IW))+ xlab(" ") 
}
#ggsave(paste0("./IW_",IW,".png"),p)
print(p)
}
}
```

```{r}
#Plot Graph for Summary Statistics
plot_insurance_summary_statistics <- function(insurance_object){
#Transpose and Shape the Summary Statistics to plot
df_to_plot = as.data.frame(t(insurance_object[[1]][[1]]))
#Transform VaR to Positive
df_to_plot[, "Avg. VaR 99.5% (RP200)"] = df_to_plot[, "Avg. VaR 99.5% (RP200)"] * -1
values = cbind(df_to_plot,1:nrow(df_to_plot))  
colnames(values)[ncol(values)] <- "Number_RC"
values = pivot_longer(values, cols = c("Initial Wealth (IW)","Avg. VaR 99.5% (RP200)","Model Premium", "Avg. Profit", "Premium with Expense Ratio"))

colors = c("red","blue","green","yellow","black")
#Meltdown the to the long format. Add a dummy variable "type" to map the different outputs of the transformation to the to be graphed data.
#First mutate call is from the ForCats package to give custom order for the graph
p = values %>% ggplot( aes(fill=name, y=value, x=1)) + 
    geom_bar(position="dodge", stat="identity") + xlab("")+ facet_grid(. ~Number_RC) 
#ggsave(paste0("./IW_",IW,".png"),p)
#Rearrange Function: 
#mutate(name = fct_relevel( 
#            "Initial Wealth (IW)", "Avg. VaR 99.5% (RP200)","Premium with #Expense Ratio", "Model Premium", "Avg. Profit" ))
print(p)

}
```

```{r}
#Graphic Functions
plot_reinsurance_distributions <- function(insurance_object){
df_to_plot = insurance_object[[2]][[2]]
for(num_RC in unique(df_to_plot$Number_RC)){
p = ggplot()
colors = c("red","blue","green","yellow","black")

  df_to_plot_simu_1= df_to_plot %>% filter(Number_RC == num_RC) %>% arrange(as.numeric(Profit))


  
p = p + theme_bw() + geom_line(data = df_to_plot_simu_1,aes(y=as.numeric(Profit),x=seq(1,length(Profit)))) +ggtitle(paste0("Profits by simulations for RC ",num_RC))+ xlab(" ") 

#ggsave(paste0("./IW_",IW,".png"),p)
print(p)
}
}
```

```{r}
#Graphic Functions
plot_ils_distributions <- function(insurance_object){
df_to_plot = insurance_object[[3]][[2]]
for(num_RC in unique(df_to_plot$Number_RC)){
p = ggplot()
colors = c("red","blue","green","yellow","black")


#Get copupon payment
coupon_payment = insurance_object[[3]][[1]][num_RC,6][[1]]

  df_to_plot_simu_1= df_to_plot %>% filter(Number_RC == num_RC) %>% arrange(as.numeric(bond_loss)) %>% mutate(outcome_ILS = coupon_payment - as.numeric(bond_loss))
  



  
p = p + theme_bw() + geom_line(data = df_to_plot_simu_1,aes(y=as.numeric(outcome_ILS),x=seq(1,length(outcome_ILS))))+ggtitle(paste0("Outcome for ILS Investor ", num_RC))+ xlab(" ") 

#ggsave(paste0("./IW_",IW,".png"),p)
print(p)
}
}
```

```{r}
#Start Analysis



#Reinsurance Matrix 1: 4 Reinsurers, 40%, 20%, 10%, 5% quota share with all insurers.
#nrow = number of reinsurers, ncol = number of insurerance companies.
reinsurance_matrix_1 = rbind(rep(0.4,5),rep(0.2,5),rep(0.1,5),rep(0.05,5))

test_outcome1 = calculate_insurance_outcomes(Model_1_Solutions, verification_set, scenario_1_IW, 1)
test_outcome2 = calculate_reinsurance_outcomes(Model_1_Solutions, verification_set, scenario_1_IW, reinsurance_matrix_1, 0)

#Scenario 2 is called capital_curve. Only one Insurance Company per setup, however, multiple simulations. So we need to loop and extract the stuff we want from it 

#Dimension of capital curve, first is number of IW_setups, which gives us the duartion of the loop We need to explicitly declare the array, because if else, the last (4th) dimension of the original array gets wiped. So we just double the array, and just take the first value.


dim_cc = dim(capital_curve)[[1]]
capital_curve_pseudo_array = array(dim = c(dim(capital_curve)[[2]],dim(capital_curve)[[3]],2)) 

capital_curve_overview = matrix(nrow = 7, ncol = dim_cc)

for (i in 1:dim_cc){
  #Calculate Value and bind to new frame. First seed the pseudo array with the double rows and return
  capital_curve_pseudo_array[,,1] = capital_curve[i,,,]
  capital_curve_pseudo_array[,,2] = capital_curve[i,,,]
  current_values_cc = calculate_insurance_outcomes(capital_curve_pseudo_array, verification_set, scenario_2_IW[i])
capital_curve_overview[,i] = cbind(current_values_cc[[1]][,1])
  
}

#Scenario 3: Constrained Optimization: 5 Insurance Companies, First and Second constrained to Large, Third to Med, Fourth and Fifth Small & Med


scenario_3_results = calculate_reinsurance_outcomes(constrained_optimization_results[1,,,], verification_set, scenario_3_IW, reinsurance_matrix_1)

#ILS Scenario 3: Constrained Optimization: 5 Insurance Companies, First and Second constrained to Large, Third to Med, Fourth and Fifth Small & Med. Declare bond_array, with nominal values for the 4 reinsurers. Take 0.25 of VaR as start value

bond_value_array = c(21,10.5,5.25,2.6) 

scenario_3_results_ils = calculate_reinsurance_ils_outcomes(constrained_optimization_results[1,,,], verification_set, scenario_3_IW, reinsurance_matrix_1,bond_value_array,1, 0.02)


#ILS Outcomes with Reinsurance Outcomes

scenario_3_results_ils_RP200 = calculate_reinsurance_ils_hypothetical_bond_outcome(constrained_optimization_results[1,,,], verification_set, scenario_4_IW, reinsurance_matrix_1,bond_value_array,1, 0.02,.99)


```

```{r}
# ILS Scenario Big Primary Insurer. Set reinsurance matrix equal to 1 to pass through bond.

#Similar to the capital curve, we need to explicitly declare the array, because if else, the last (4th) dimension of the original array gets wiped. Fixing this is a to-do of a later version

# IMPORTANT: Because we pass 100% through the reinsurance sector, there seems to be a bug that counts the profit and outcomes double. Will be fixed in the next version

#ils_pseudo_array = array(dim = #c(dim(ils_beazley_case)[[2]],dim(ils_beazley_case)[[3]],2))


#Get the results of the main optimization [first simulation result]
#ils_pseudo_array[,,1] = ils_beazley_case[1,,,1]
#ils_pseudo_array[,,2] = ils_beazley_case[1,,,1]


#Bond Value, double matrix for input

ils_reinsurance_matrix = matrix(c(1,1), nrow = 1, ncol = 2)
bond_value = c(5e3)
#ils_bond_results_1 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value,1, 0.02,.995)

#Capital Curve ILS

#dim_cc = dim(ils_beazley_case)[[1]]
#capital_curve_ils_pseudo_array = array(dim = c(dim(ils_beazley_case)[[2]],dim(ils_beazley_case)[[3]],2)) 

capital_curve_overview = matrix(nrow = dim_cc, ncol = 1)

for (i in 1:1){
  #Calculate Value and bind to new frame. First seed the pseudo array with the double rows and return
  #capital_curve_ils_pseudo_array[,,1] = ils_beazley_case[i,,,]
  #capital_curve_ils_pseudo_array[,,2] = ils_beazley_case[i,,,]
#  current_values_cc = calculate_insurance_outcomes(capital_curve_ils_pseudo_array, verification_set, scenario_4_CC_IW[i])
  print(i)
capital_curve_overview[i,1] = current_values_cc[[1]][4,1]
  
}
print(capital_curve_overview)

#Profit Insurer with $35M,currently hard coded.

scenario_35M_noILS = 1776
#print(ils_bond_results_1)

```

```{r}
#Bond Values with different attachtments points:

bond_value_attatchment = c(5e3)

#ils_attatchment1 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment,1, 0.02,.995)

#ils_attatchment2 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment,1, 0.02,.99)

#ils_attatchment3 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment,1, 0.02,.98)

different_attatchment_points = rbind(ils_attatchment1[[3]][[1]],ils_attatchment2[[3]][[1]],ils_attatchment3[[3]][[1]])

print(different_attatchment_points)
print(ils_attatchment1)
```




```{r}

#Different Bond Values
bond_value_attatchment = c(5e3,6e3,7e3,8e3,9e3,10e3)

#ils_different_bond_value1 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment[1],1, 0.02,.995)

#ils_different_bond_value2 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment[2],1, 0.02,.995)

#ils_different_bond_value3 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment[3],1, 0.02,.995)

#ils_different_bond_value4 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment[4],1, 0.02,.995)

#ils_different_bond_value5 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment[5],1, 0.02,.995)

#ils_different_bond_value6 = calculate_reinsurance_ils_hypothetical_bond_outcome(ils_pseudo_array, verification_set, scenario_4_IW, ils_reinsurance_matrix,bond_value_attatchment[6],1, 0.02,.995)

different_bond_values = rbind(ils_different_bond_value1[[3]][[1]],ils_different_bond_value2[[3]][[1]],ils_different_bond_value3[[3]][[1]],ils_different_bond_value4[[3]][[1]],ils_different_bond_value5[[3]][[1]],ils_different_bond_value6[[3]][[1]])

print(different_bond_values)
```






```{r}
#Start Graphics
plot_insurance_distributions(ils_different_bond_value1)



```






